### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by Individuum92** [aarnhub/instagram-scraper-python#2]
Hi,

when I execute the script I receive the following error message back:

`598 followers
2021-02-15 12:54:29.003589
Traceback (most recent call last):
  File "followers-scraper.py", line 68, in <module>
    scr1 = driver.find_element_by_xpath('/html/body/div[5]/div/div/div[2]/ul/div/li[%s]' % i)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div/div/div[2]/ul/div/li[1]"}
  (Session info: chrome=88.0.4324.146)
`

It seems that there is a wrong path the script is trying to navigate to?
Which Element is the script looking for here?
Can you mayb paste a fix?

Great Job!
Thanks a lot

**Comment by Individuum92** [comment]
Any Idea here?

**Comment by aleeberto** [comment]
For scrape following you have to change in the for cycle.
From: 
`driver.find_element(By.XPATH, '/html/body/div[5]/div/div/div[2]/ul/div/li[%s]' % i)`
To:
`driver.find_element(By.XPATH, '/html/body/div[5]/div/div/div[3]/ul/div/li[%s]' % i)`

This will work only for scrape following and not for follower
